### ISSUE TITLE
Dockers for debugging

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#10]
We should have a docker composer file that can automatically deploy code for test.
- MySQL (Need import schema)
- PHP & Nginx

**Comment by seadog007** [comment]
Done by #13, Thanks to @rexx0520 <3

**Comment by oToToT** [comment]
encounter these 2 error
```
ERROR: for docker_php_1  Cannot start service php: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: permission denied": unknown

ERROR: for php  Cannot start service php: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```
while running `docker-compose up -d` in docker folder

**Comment by lekoOwO** [comment]
https://github.com/seadog007/breach.tw/issues/10#issuecomment-522336745 Not sure if @seadog007 's commit broke the docker-compose. Will test tomorrow.
