### ISSUE TITLE
Auto import script (or even a web interface)

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#12]
Given the list (either hash list or original data list), it can automatically import it into the system.
There are several steps

- [x] (Optional) If it is the original data list, then it will need to convert to the hashed list first, which can be done by a simple python script
```python
from hashlib import sha1
import sys

iname = sys.argv[1]
oname = iname + '_hashed'

with open(iname, 'r') as ifile:
    with open(oname, 'w') as ofile:
        for line in ifile:
            line = line.rstrip()
            digest = sha1(line).hexdigest()
            ofile.write('{0}\n'.format(digest))
```

- [x] Add a row into `breach_source` table, which include 
1. name
2. description (default `Text("待補")`)
3. round_k (default `Int(0)`)
4. comment
5. time
6. major (if `round_k` > 5 then 1)
7. file (if is Google Hacking)
8. type (now only 4 type `Text(政府單位)`, `Text(教育機構)`, `Text(民間企業)`, `Text(其他)`)

- [x] Add rows into `source_item` table, which contains
1. source (primary id from `breach_source` table)
2. item (primary id from `breach_item` table)

- [x] Import hashes into `breach_log` table, which can divide into few steps
1. Import hashes into `breach_log` table
2. Update source to the specific id (primary id from `breach_source` table)
The example SQL will be something like below: 
```SQL
LOAD DATA INFILE '/tmp/hash.txt' INTO TABLE `breach_log` CHARACTER SET utf8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' (`hash`);
UPDATE `breach_log` SET `source`=999 WHERE `source` IS NULL;
```

- [x] Generate the email list from the `subscribers` table
the example SQL will like this
```SQL
SELECT `email` FROM `subscribers` WHERE `hash` IN (SELECT `hash` FROM `breach_log` WHERE `source` = 999) AND email_verify = 1;
```

**Comment by seadog007** [comment]
DB API Interface #33

**Comment by seadog007** [comment]
Backend @rexx0520
Frontend @gnehs

**Comment by seadog007** [comment]
The design patten of file processor is pipeline, and it should looks like this
`[file input] -> s1pp[0] -> s1pp[1] -> s1pp[n] -> s1_to_s2 -> s2pp[0] -> s2pp[1] -> s2pp[n] -> combiner -> [inserter -> db]`
`s1pp` are line filter/pre-processor
`s2pp` are `[name, id]` filter/pre-processor

**Comment by lekoOwO** [comment]
> The design patten of file processor is pipeline, and it should looks like this
> `[file input] -> s1pp[0] -> s1pp[1] -> s1pp[n] -> s1_to_s2 -> s2pp[0] -> s2pp[1] -> s2pp[n] -> combiner -> [inserter -> db]`
> `s1pp` are line filter/pre-processor
> `s2pp` are `[name, id]` filter/pre-processor

https://github.com/seadog007/breach.tw/pull/44

**Comment by seadog007** [comment]
mail function in #70
