### ISSUE TITLE
API for public, which require noCAPTCHA for now

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#15]
Since there are apis for the website, we should publish the api for the public, and which require some proof of work for preventing abuse.

The system ideally should be stateless, contains two functions

- [ ] Generate challenge, and sign with the given key (written in `config.php`), then distribute to users 
- [ ] Verify the challenge and the work from user

but stateless PoW need some mechanism to prevent replay attack.

**Comment by seadog007** [comment]
@koru1130 any idea?

**Comment by seadog007** [comment]
cc @oToToT

**Comment by koru1130** [comment]
use request self as parameter
e.g. (pseudo code)
slice(toString(hash(request + blah)), n) == repeat("0", n)

**Comment by lekoOwO** [comment]
hashing algorithm might do it.
By asking client to calculate `nonce` which makes `hash(request + nonce)` start with several `0` bit, we can achieve PoW with a small computational cost

**Comment by oToToT** [comment]
How about subscribe API?

**Comment by seadog007** [comment]
Not really plan to do that, since that is part of the website function and there will be no need to subscribe lots of hash.
