### ISSUE TITLE
Need some example CLI clients for #15

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#16]
Need some example CLI clients for #15
Single file scripts are ideal
- [x] Python
- [x] Node.js
- [x] PHP
- [x] Shell Script

There will be a new orphan branch for this

Below is the example code for calculate nonce in Python
```python
import hashlib

be = 'hash'
nonce = 0
diff = 5

while 1 :
	x = be + str(nonce)
	if hashlib.sha1(x).hexdigest()[:diff] == 'a' * diff :
		print("done",x,nonce,hashlib.sha1(x).hexdigest()[:diff])
		break
	else :
		nonce = nonce + 1
```

**Comment by seadog007** [comment]
BTW, the api address is
https://breach.tw/api/search.php?mode=pow&hash=xxxxxxxxxxxxxxxxxxxx&nonce=123456

**Comment by seadog007** [comment]
The name of the branch is `example_api_clients`

**Comment by lekoOwO** [comment]
node.js version done https://github.com/seadog007/breach.tw/pull/22

**Comment by lekoOwO** [comment]
python version done https://github.com/seadog007/breach.tw/pull/23

**Comment by t510599** [comment]
php version done #32

**Comment by t510599** [comment]
go version done #35

**Comment by seadog007** [comment]
Should be good

**Comment by seadog007** [comment]
C++ version in #36
