### ISSUE TITLE
Need API docs for #15

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#18]
Just a doc

**Comment by oToToT** [comment]
# # breach.tw API Document
This document contains how to use the api
#### NOTE
* All the GET request arguments are sent in the URL
* All the respond bodies are json format
---
#### search.php
```http
 GET /api/search.php
```
* Check data breaches
	* Request Argument
		* hash: *(required)* The sha1 of `姓名 + 身份證字號後五碼`.
		* mode: *(required)* `pow` or `recaptcha`.
		* nonce: (required if mode is set to `pow`) The string which makes the first 5 sha1 of `hash + nonce` equals to `aaaaa`.
		* token: (required if mode is set to `recaptcha`) The user response token provided by the reCAPTCHA client-side integration on your site.
	* Respond Body
		* status: The bool indicate that whether the query being failed or not.
		* error: The string of the error message.
		* result: The object which contain the information of leaked data.
		 		* key: The source of data breach
		 		* value: The array of strings which indicate which information was being leaked.
---
#### subscribe.php
```http
 GET /api/subscribe.php
```

---
#### stat.php
```http
 GET /api/stat.php
```

**Comment by seadog007** [comment]
Copy the above doc to repo on https://github.com/seadog007/breach.tw/commit/f6e7852b8ed42694795fe0f993ab1aabdc2dba78
Thank @oToToT
