### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by oToToT** [seadog007/breach.tw#2]
In windows 10 with resolution 1920x1080.

You will see a blank line right beside your window in most browsers.

![Example Image](https://i.imgur.com/R8CGOOy.png)

**Comment by oToToT** [comment]
The main reason is that 100vw won't count the size of the bar on the right hand, so it might contain a white bar.

**Comment by seadog007** [comment]
This is very old version of tocas-ui, upgrade might fix it.

**Comment by t510599** [comment]
Fixed by changing `width: 100vw` to `width: 100%`.  

![2019-10-02 16-29-49 的螢幕擷圖](https://user-images.githubusercontent.com/18533304/66029450-e33b8e00-e531-11e9-8ca4-c46da09ccc75.png)

**Comment by seadog007** [comment]
Is this fix in v2.0 ?

**Comment by seadog007** [comment]
@oToToT @t510599 Try this
https://test.breach.tw

**Comment by oToToT** [comment]
I think this problem has been fixed in v2.0, but the problem in home page doesn't.

**Comment by seadog007** [comment]
index.php is remain unchanged, and that's another issue
