### ISSUE TITLE
"Frequently Asked Questions" page

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#20]
This page should contain some common questions.

- [x] What should I do after breaches? （個資被洩露，我應該怎麼做？）
- [x] Are we fraud?（這是詐騙嗎？）
- [x] How to use API?（API 要怎麼用？）
- [x] What is hash?（雜湊是什麼？）
- [x] What email address are notifications sent from? （通知會從哪個電子郵件地址寄送？）

Please feel free to provide more questions under this issue

**Comment by seadog007** [comment]
Example of the first question
```
只能多多注意有沒有被拿去註冊奇怪的帳號
平常也要多多注意不同網站不要共用密碼
畢竟很多個資不是說改就能改的
密碼也儘量不要使用身分證或生日的組合
```

Here need your help @koru1130

**Comment by koru1130** [comment]
### What should I do after breaches? （個資被洩露，我應該怎麼做？）
　　個資一旦被外洩就很難收回，但您可以盡力將傷害降到最低。例如檢查是否有不同網站共用密碼，注意個資有沒有被拿去註冊奇怪的帳號。另外密碼也盡量避免使用身分證或生日的組合，以免有心人士透過外洩的個資猜到您的密碼。

### Are we fraud?（這是詐騙嗎？）
　　請您放心，這個網站只是一群熱愛資安的青年自發設立的網站，旨在加強大眾的資安意識。在您按下送出搜尋按鈕後，您的資料會透過雜湊的方式去識別化，我們不會也無法知道您的姓名及身份證字號。

### How to use API?（API 要怎麼用？）
　　我們目前還在撰寫 API 文件，若有急需請洽 t.me/seadog007

### What is hash?（雜湊是什麼？）
　　雜湊是一種對資料的處理方法，可將任意資料轉換成固定長度的字串。將兩筆不同的資料雜湊後，得到相同結果的機率極低。而雜湊後的字串極難轉換回原本的資料。透過這兩個特性，我們可以在不知道您的姓名及身分證字號的情況下，辨別資料庫內是否含有您的資料。

**Comment by seadog007** [comment]
@koru1130 I think we can provide more evidence for the section "Are we fraud?" since this project is for AIS3 and also open source for public review

**Comment by seadog007** [comment]
Added `What email address are notifications sent from? （通知會從哪個電子郵件地址寄送？）` to todo list
