### ISSUE TITLE
Duplicated string in breach data

### ISSUE THREAD

**Issue by t510599** [seadog007/breach.tw#34]
![Screenshot_20191002-220232](https://user-images.githubusercontent.com/18533304/66050819-78ee1200-e560-11e9-90f1-33087042f754.png)

**Comment by seadog007** [comment]
This should be db issue not programming issue :P
<img width="794" alt="截圖 2019-10-03 上午12 00 00" src="https://user-images.githubusercontent.com/5138409/66060804-dbe7a500-e570-11e9-801d-ce914d5fbe87.png">
Resolved
