### ISSUE TITLE
Inconsistent rendering & design issues

### ISSUE THREAD

**Issue by Still34** [seadog007/breach.tw#4]
1. tocas.css does not seems to be fully optimized for the design that the website uses.
    - The homepage sometimes have issues rendering across unusual dimension sizes (depending on the dimensions, the header will render either [not render at all](https://i.imgur.com/nrIfzwc.png), or [render twice](https://i.imgur.com/PxLx7Wv.png)).
    -  Additionally, this CSS condones bad practices using `*{font-family:"Open Sans","Noto Sans TC","Meiryo","微軟正黑體","Microsoft JhengHei";box-sizing:border-box;letter-spacing:-0.02em}`. 
    - The issue lies in that no additional generic fontset is set after JhengHei. Furthermore, JhengHei may or may not be shipped in future versions of Windows, as Microsoft has begun to switch to `Microsoft YaHei`. 
2. There are a lot of weird unclosed (random `</h3>` out of nowhere) or unnecessarily closed HTML tags (`<input>` is a root tag, which does not require closure) present in some parts of the PHP code.
3. CSS files are scattered across PHP files, which may lead to duplication and further issues down the road for readability and debuggability.

**Comment by seadog007** [comment]
First one seem to be duplicate with #3. Close #3 since this issue has more detail.

**Comment by seadog007** [comment]
I will try to fix weird tags for now.
Also need help for CSS QQ 
@YamiOdymel may help, but he is under brainwashing right now QQ

**Comment by YamiOdymel** [comment]
I got conscripted which ends in the next week,

and I've already planned to release Tocas 3 or 4 which is the re-write version of the original Tocas 2.x.

The font-family is a headache for me, since there're many users from the different countries, I might remove it but the line-hight will be "uncontrollable" due to the different system fonts.

I haven't figured out the answer about how to solve it but I will try.

**Comment by Still34** [comment]
> I got conscripted which ends in the next week,
> 
> and I've already planned to release Tocas 3 or 4 which is the re-write version of the original Tocas 2.x.
> 
> The font-family is a headache for me, since there're many users from the different countries, I might remove it but the line-hight will be "uncontrollable" due to the different system fonts.
> 
> I haven't figured out the answer about how to solve it but I will try.

The major problem I had with the `*` part was mostly the `font-family`, as it prioritizes a custom Latin font, followed by a `zh-tw` font, then a `ja-jp` font, then another set of `zh-tw` fonts - the problem lies in the fact that there is no fallback font family for the Latin character sets, and will therefore default to a font that is decided by the web browser itself's default. 

Additionally, as pointed out in the issue description itself, Microsoft JhengHei is a legacy font at this point, per [Microsoft's documentation](https://docs.microsoft.com/en-us/typography/font-list/microsoft-jhenghei). While there is nothing wrong with keeping the said font as part of the fallback font family, I feel like Microsoft YaHei should be added and prioritized first. 

Anyhow, this is just my opinion and is kinda beyond the scope of this issue so I'll stop rambling now :p

**Comment by seadog007** [comment]
Solved by #45
