### ISSUE TITLE
Move out debug mode switch from config.json to environment variable for admin panel

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#47]
Just move this out
https://github.com/seadog007/breach.tw/blob/admin_panel/config.json#L9

**Comment by seadog007** [comment]
cc @rexx0520

**Comment by lekoOwO** [comment]
no

**Comment by lekoOwO** [comment]
https://github.com/rexx0520/breach.tw/commit/b1b53ee986722ce5923934370738fc7bc5d40e11

**Comment by lekoOwO** [comment]
im sorry :D
