### ISSUE TITLE
Empty input shouldn't be processed

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#52]
<img width="754" alt="截圖 2019-10-11 下午4 45 23" src="https://user-images.githubusercontent.com/5138409/66633792-97ca6380-ec46-11e9-82e1-2a4f9b2db9ea.png">

**Comment by lekoOwO** [comment]
Since this is a backend admin system, i dont think we need a fool-proof design.
May be discussed.

**Comment by seadog007** [comment]
but this is without any params
