### ISSUE TITLE
IE Compatible

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#60]
It should be compatible for IE 9+ (or 10+) since there are still some user using IE for browsing our website

**Comment by t510599** [comment]
sweetalert2 can only be used on IE 11 (polyfill should be included).  
See https://github.com/sweetalert2/sweetalert2/blob/master/README.md#browser-compatibility .

**Comment by seadog007** [comment]
We should have something like this

# 你知道嗎
### 過時的瀏覽器有可能會增加個資外洩的風險喔

**Comment by t510599** [comment]
Add some `!!!!` (X

**Comment by seadog007** [comment]
#61
