### ISSUE TITLE
Task Progress and Status

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#83]
There is no progress and status for the task, user will never knows if the task finished or not.
Also this should include input lines count and output lines count

<img width="704" alt="截圖 2019-10-13 下午3 57 47" src="https://user-images.githubusercontent.com/5138409/66712682-bd847380-edd2-11e9-9c01-e7e2c2de916e.png">

**Comment by seadog007** [comment]
```
{ 
    "input_line":100,
    "output_line":50,
    "time_cost":120,
    "status":"done/processing",
    "start_time":"time",
    "end_time":"time/null",
    "pps":{ 
        "s1":[ 
            { 
                "name":"s1pp2",
                "filtered":24
            },
            { 
                "name":"s1pp1",
                "filtered":1
            }
        ],
        "s2":[ 
            { 
                "name":"s2pp5",
                "filtered":24
            }
        ],
        "s1_to_s2":1
    }
}
```
The output format I expect is like this

**Comment by lekoOwO** [comment]
> ```
> { 
>     "input_line":100,
>     "output_line":50,
>     "time_cost":120,
>     "status":"done/processing",
>     "start_time":"time",
>     "end_time":"time/null",
>     "pps":{ 
>         "s1":[ 
>             { 
>                 "name":"s1pp2",
>                 "filtered":24
>             },
>             { 
>                 "name":"s1pp1",
>                 "filtered":1
>             }
>         ],
>         "s2":[ 
>             { 
>                 "name":"s2pp5",
>                 "filtered":24
>             }
>         ],
>         "s1_to_s2":1
>     }
> }
> ```
> 
> The output format I expect is like this

no im going to return progress when it's not done yet

**Comment by seadog007** [comment]
@rexx0520 what do you mean by that

**Comment by lekoOwO** [comment]
3/5

**Comment by seadog007** [comment]
@rexx0520 ok
