### ISSUE TITLE
Request failed when editing source

### ISSUE THREAD

**Issue by seadog007** [seadog007/breach.tw#90]
<img width="387" alt="截圖 2019-10-14 下午5 17 35" src="https://user-images.githubusercontent.com/5138409/66744768-d878e580-eeaf-11e9-9083-20bb126e2cca.png">

<img width="320" alt="截圖 2019-10-14 下午6 23 00" src="https://user-images.githubusercontent.com/5138409/66744736-c5feac00-eeaf-11e9-8681-e78326a4996b.png">

**Comment by gnehs** [comment]
笨雷雷：（

**Comment by lekoOwO** [comment]
n
笨料料 :(

**Comment by seadog007** [comment]
@rexx0520 笨笨後端

**Comment by lekoOwO** [comment]
n 笨笨資料庫

**Comment by seadog007** [comment]
@rexx0520 快去修la吵P

**Comment by gnehs** [comment]
@seadog007 笨笨海豹

**Comment by lekoOwO** [comment]
@seadog007 笨海豹

**Comment by gnehs** [comment]
![image](https://user-images.githubusercontent.com/16719720/66745302-2e01c200-eeb1-11e9-80be-2ce6024e6df1.png)
我們轉盤決定誰修
沒
